#!/usr/bin/env bash
# Runs on every Codespace start: secrets (first time), public address, TURN credentials, the stack.
set -euo pipefail
cd "$(dirname "$0")/../.."
ROOT=$PWD
C=infra/compose
# RS_COMPOSE_EXTRA / RS_PUBLIC_ORIGIN exist only to rehearse this script outside a Codespace.
compose() {
  docker compose -f "$C/docker-compose.yml" -f infra/codespace/compose.yml \
    ${RS_COMPOSE_EXTRA:+-f "$RS_COMPOSE_EXTRA"} "$@"
}

DOMAIN="${CODESPACE_NAME:?not running in a Codespace}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
ORIGIN="${RS_PUBLIC_ORIGIN:-https://$DOMAIN}"
DOMAIN="${ORIGIN#*://}"

# ---- secrets: generated once, kept in the Codespace only (git-ignored) ----
mkdir -p "$C/secrets"
if [ ! -f "$C/secrets/pg_password" ]; then
  echo "==> Generating secrets"
  openssl rand -hex 24 > "$C/secrets/pg_password"
  KEYS=$(node apps/control/dist/cli.js keys:generate)
  echo "$KEYS" | tail -n 1 > "$C/secrets/seal_secret"
  # Docker mounts file secrets with these permissions and the supervisor runs as a non-root user:
  # the files must be world-readable, so the directory is what keeps other host users out.
  chmod 700 "$C/secrets"
  chmod 644 "$C/secrets/"*
  {
    echo "$KEYS" | grep '^RS_SEAL_PUBLIC_KEY='
    echo "RS_TOTP_KEY=$(openssl rand -base64 32)"
    echo "MEDIAMTX_INTERNAL_USER=supervisor"
    echo "MEDIAMTX_INTERNAL_PASS=$(openssl rand -hex 24)"
  } > "$C/.env.codespace-secrets"
  chmod 600 "$C/.env.codespace-secrets"
fi

# ---- .env: rebuilt every start (the Codespace address and TURN secrets can change) ----
{
  echo "# Generated by infra/codespace/start.sh. Do not edit; do not commit."
  echo "DOMAIN=$DOMAIN"
  echo "PUBLIC_ORIGIN=$ORIGIN"
  echo "WHIP_PUBLIC_BASE=$ORIGIN/whip"
  echo "PUBLIC_IP=127.0.0.1"
  echo "DATABASE_URL=postgres://raelstream:$(cat "$C/secrets/pg_password")@postgres:5432/raelstream"
  cat "$C/.env.codespace-secrets"
  if [ -n "${RS_TURN_CF_KEY_ID:-}" ] && [ -n "${RS_TURN_CF_API_TOKEN:-}" ]; then
    echo "RS_TURN_CF_KEY_ID=$RS_TURN_CF_KEY_ID"
    echo "RS_TURN_CF_API_TOKEN=$RS_TURN_CF_API_TOKEN"
    # Nothing is reachable directly in a Codespace; skip straight to the relay.
    echo "RS_ICE_TRANSPORT_POLICY=relay"
  fi
  # GitHub's port forwarding rewrites every browser Origin to http://localhost:8080. The CSRF header
  # and SameSite=Strict cookies still protect state-changing requests.
  echo "RS_EXTRA_ALLOWED_ORIGINS=http://localhost:8080"
} > "$C/.env"
chmod 600 "$C/.env"
node infra/codespace/turn-env.mjs "$C/.env.mediamtx-turn"

# ---- the stack ----
echo "==> Starting the stack (the first start builds images; this takes a few minutes)"
compose up -d --build
for _ in $(seq 1 90); do
  curl -fsS http://localhost:8080/api/health >/dev/null 2>&1 && break
  sleep 2
done

# Phones cannot sign in to GitHub, so the port must be public (the app has its own sign-in).
gh codespace ports visibility 8080:public -c "$CODESPACE_NAME" >/dev/null 2>&1 \
  && PORT_NOTE="public" \
  || PORT_NOTE="NOT public yet: open the PORTS tab, right-click port 8080 → Port Visibility → Public"

# ---- stand-in platforms, added once ----
if [ ! -f "$C/.codespace-destinations" ]; then
  echo "test-facebook-key-0001" | compose exec -T control node dist/cli.js destination:add \
    --platform facebook --label "Test Facebook (stand-in)" --server rtmp://rs-test-platform:1935/watch/facebook
  echo "test-youtube-key-0002" | compose exec -T control node dist/cli.js destination:add \
    --platform youtube --label "Test YouTube (stand-in)" --server rtmp://rs-test-platform:1935/watch/youtube \
    --auto-publish yes
  touch "$C/.codespace-destinations"
fi

TURN_NOTE="configured"
grep -q '^MTX_WEBRTCICESERVERS2_0_URL' "$C/.env.mediamtx-turn" || TURN_NOTE="NOT configured: private test and Go live cannot connect (see the guide, step 2)"

cat <<BANNER

  ───────────────────────────────────────────────────────────────────
  raelstream test studio is running

  Studio (Dell):      $ORIGIN/studio
  What viewers see:   $ORIGIN/watch/facebook/test-facebook-key-0001/
                      $ORIGIN/watch/youtube/test-youtube-key-0002/

  Port 8080:          $PORT_NOTE
  TURN relay:         $TURN_NOTE

  First time?  Create your owner account:  bash infra/codespace/create-owner.sh
  ───────────────────────────────────────────────────────────────────
BANNER
cd "$ROOT"
